import type {
  Branch, Review, Competitor, AlertItem,
  DashboardMetrics, RatingHistory, ComplaintStat
} from '@/types'

export const BRANCHES: Branch[] = [
  // CRITICAL — real 2GIS data
  {
    id: 'b-bayterekova',
    name: 'Садыхан (соц. аптека)',
    address: 'ул. Байтерекова, 53',
    city: 'Алматы', district: 'Алмалинский',
    rating: 2.3, reviewCount: 258, negativeCount: 189,
    answeredCount: 140, unansweredCount: 118,
    healthScore: 18, ratingTrend: -0.3, topIssue: 'Качество и сервис',
    status: 'crisis', lat: 43.255, lng: 76.945,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-apt17',
    name: 'Аптека №17',
    address: 'мкр. 3-й, 20а',
    city: 'Алматы', district: 'Ауэзовский',
    rating: 2.5, reviewCount: 163, negativeCount: 112,
    answeredCount: 90, unansweredCount: 73,
    healthScore: 22, ratingTrend: -0.4, topIssue: 'Низкий сервис',
    status: 'crisis', lat: 43.233, lng: 76.854,
    phone: '+7 727 3XX-XX-XX', hours: 'Круглосуточно',
  },
  {
    id: 'b-apt9',
    name: 'Аптека №9',
    address: 'мкр. Мамыр-2, 3',
    city: 'Алматы', district: 'Ауэзовский',
    rating: 2.6, reviewCount: 143, negativeCount: 96,
    answeredCount: 78, unansweredCount: 65,
    healthScore: 28, ratingTrend: -0.2, topIssue: 'Грубость, обслуживание',
    status: 'crisis', lat: 43.215, lng: 76.835,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-seyfullina168',
    name: 'Садыхан (сеть аптек)',
    address: 'пр. Сейфуллина, 168Б',
    city: 'Алматы', district: 'Алмалинский',
    rating: 3.1, reviewCount: 92, negativeCount: 54,
    answeredCount: 60, unansweredCount: 32,
    healthScore: 35, ratingTrend: -0.1, topIssue: 'Санитария, запах',
    status: 'critical', lat: 43.268, lng: 76.930,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-apt2',
    name: 'Аптека №2',
    address: 'ул. Гоголя, 140',
    city: 'Алматы', district: 'Алмалинский',
    rating: 3.4, reviewCount: 399, negativeCount: 180,
    answeredCount: 300, unansweredCount: 99,
    healthScore: 40, ratingTrend: -0.1, topIssue: 'Ассортимент, цены',
    status: 'critical', lat: 43.270, lng: 76.920,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-apt12',
    name: 'Аптека №12',
    address: 'пр. Достык, 91/2 (БЦ ARDIN)',
    city: 'Алматы', district: 'Медеуский',
    rating: 3.4, reviewCount: 200, negativeCount: 95,
    answeredCount: 160, unansweredCount: 40,
    healthScore: 42, ratingTrend: 0.0, topIssue: 'Грубость, телефон',
    status: 'critical', lat: 43.236, lng: 76.956,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-nurlutan',
    name: 'Садыхан (сеть аптек)',
    address: 'ул. Нурлы тан, 2г',
    city: 'Алматы', district: 'Алатауский',
    rating: 3.3, reviewCount: 110, negativeCount: 60,
    answeredCount: 80, unansweredCount: 30,
    healthScore: 38, ratingTrend: -0.2, topIssue: 'Цены, скидочная карта',
    status: 'critical', lat: 43.195, lng: 76.810,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-turksibbazar',
    name: 'Садыхан (сеть аптек)',
    address: 'пр. Суюнбая, 251 (Рынок Турксиб)',
    city: 'Алматы', district: 'Турксибский',
    rating: 3.9, reviewCount: 19, negativeCount: 5,
    answeredCount: 14, unansweredCount: 5,
    healthScore: 62, ratingTrend: 0.1, topIssue: '—',
    status: 'warning', lat: 43.315, lng: 77.015,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-apt3',
    name: 'Аптека №3',
    address: 'ул. Толе би, 201',
    city: 'Алматы', district: 'Алмалинский',
    rating: 3.5, reviewCount: 130, negativeCount: 55,
    answeredCount: 100, unansweredCount: 30,
    healthScore: 48, ratingTrend: 0.0, topIssue: 'Очередь',
    status: 'warning', lat: 43.265, lng: 76.905,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-apt6',
    name: 'Аптека №6',
    address: 'ул. Пушкина, 41',
    city: 'Алматы', district: 'Алмалинский',
    rating: 3.6, reviewCount: 145, negativeCount: 50,
    answeredCount: 120, unansweredCount: 25,
    healthScore: 52, ratingTrend: 0.1, topIssue: 'Цены',
    status: 'warning', lat: 43.272, lng: 76.912,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  // ASTANA
  {
    id: 'b-ast-anetbaba',
    name: 'Садыхан',
    address: 'ул. Анет баба, 2',
    city: 'Астана', district: 'Есильский',
    rating: 3.9, reviewCount: 490, negativeCount: 110,
    answeredCount: 420, unansweredCount: 70,
    healthScore: 58, ratingTrend: 0.0, topIssue: 'Телефон (не берут)',
    status: 'warning', lat: 51.112, lng: 71.448,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-ast-momyshuly',
    name: 'Садыхан',
    address: 'пр. Момышулы, 10/2',
    city: 'Астана', district: 'Сарыаркинский',
    rating: 3.9, reviewCount: 280, negativeCount: 65,
    answeredCount: 230, unansweredCount: 50,
    healthScore: 60, ratingTrend: 0.1, topIssue: 'Скорость обслуживания',
    status: 'warning', lat: 51.135, lng: 71.420,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  // GOOD branches
  {
    id: 'b-seyfullina422',
    name: 'Садыхан (соц. аптека)',
    address: 'пр. Сейфуллина, 422',
    city: 'Алматы', district: 'Бостандыкский',
    rating: 4.2, reviewCount: 178, negativeCount: 28,
    answeredCount: 165, unansweredCount: 13,
    healthScore: 72, ratingTrend: 0.2, topIssue: 'Нарушение режима работы',
    status: 'warning', lat: 43.245, lng: 76.925,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-taraz23',
    name: 'Аптека №23',
    address: 'мкр. Аса, 6а',
    city: 'Тараз', district: 'Жамбылский',
    rating: 4.4, reviewCount: 95, negativeCount: 8,
    answeredCount: 88, unansweredCount: 7,
    healthScore: 84, ratingTrend: 0.3, topIssue: 'Нарушение расписания (ред.)',
    status: 'good', lat: 42.905, lng: 71.398,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
  {
    id: 'b-mamyr2',
    name: 'Садыхан',
    address: 'мкр. Мамыр-2, 3 (новый)',
    city: 'Алматы', district: 'Ауэзовский',
    rating: 4.8, reviewCount: 329, negativeCount: 12,
    answeredCount: 318, unansweredCount: 11,
    healthScore: 93, ratingTrend: 0.4, topIssue: '—',
    status: 'good', lat: 43.220, lng: 76.840,
    phone: '+7 707 349-49-49', hours: 'Круглосуточно',
  },
]

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    branchId: 'b-ast-momyshuly',
    branchName: 'Садыхан',
    branchAddress: 'пр. Момышулы, 10/2, Астана',
    authorName: 'Эль ✅',
    authorInitials: 'ЭЛ',
    rating: 1,
    text: 'Зачем поднимать трубку, заставлять ждать, а потом бросать трубку? Трудно ответить, есть ли препарат в наличии или нет — не поднимайте тогда.',
    sentiment: 'negative', severity: 'high',
    categories: ['phone'],
    hasReply: true,
    replyText: 'Эль, добрый день! Примите наши извинения за доставленные неудобства. Нам искренне жаль, что Вам пришлось столкнуться с такой ситуацией.',
    publishedAt: '2025-06-20T10:00:00Z',
    source: '2gis', aiRiskScore: 72,
  },
  {
    id: 'r2',
    branchId: 'b-apt12',
    branchName: 'Аптека №12',
    branchAddress: 'пр. Достык, 91/2, Алматы',
    authorName: 'S M',
    authorInitials: 'SM',
    rating: 1,
    text: 'Очень неприятный и грубый фармацевт — задаёшь вопросы, игнорирует; переспрашиваешь — игнорирует. Так ещё и с недовольным лицом, ни привета ни пока.',
    sentiment: 'negative', severity: 'critical',
    categories: ['rudeness'],
    hasReply: false,
    publishedAt: '2025-05-14T09:30:00Z',
    source: '2gis', aiRiskScore: 91,
  },
  {
    id: 'r3',
    branchId: 'b-apt12',
    branchName: 'Аптека №12',
    branchAddress: 'пр. Достык, 91/2, Алматы',
    authorName: 'Alexey Smart',
    authorInitials: 'AS',
    rating: 1,
    text: 'Рабочий день, 13:30. Звоню на номер телефона, автоответчик просит нажать двоечку. Минута гудков, затем сброс. Одна звезда за качество обслуживания.',
    sentiment: 'negative', severity: 'high',
    categories: ['phone', 'speed'],
    hasReply: true,
    replyText: 'Alexey, добрый день! Благодарим за ваше обращение. Мы приняли его в работу и обязательно проведём проверку.',
    publishedAt: '2025-01-13T14:00:00Z',
    source: '2gis', aiRiskScore: 68,
  },
  {
    id: 'r4',
    branchId: 'b-nurlutan',
    branchName: 'Садыхан',
    branchAddress: 'ул. Нурлы тан, 2г, Алматы',
    authorName: 'Makpal',
    authorInitials: 'МК',
    rating: 1,
    text: 'Магнерот 500: у вас 2430 тг, в Каспи — 2035 тг. 400 тг на дороге не валяются. Сервис хромает — скидочная карта не работает, информация не совпадает по филиалам.',
    sentiment: 'negative', severity: 'medium',
    categories: ['price', 'subscription'],
    hasReply: true,
    replyText: 'Makpal, добрый день! Благодарим вас за обратную связь и подробное описание ситуации.',
    publishedAt: '2025-04-10T11:00:00Z',
    source: '2gis', aiRiskScore: 55,
  },
  {
    id: 'r5',
    branchId: 'b-seyfullina422',
    branchName: 'Садыхан',
    branchAddress: 'пр. Сейфуллина, 422, Алматы',
    authorName: 'Юрий',
    authorInitials: 'ЮР',
    rating: 2,
    text: 'Поменяйте пожалуйста: круглосуточно написано, третья аптека вашего филиала не открывает.',
    sentiment: 'negative', severity: 'medium',
    categories: ['schedule'],
    hasReply: true,
    replyText: 'Здравствуйте, Юрий! Спасибо Вам за информацию. Мы сожалеем о сложившейся ситуации.',
    publishedAt: '2025-03-22T06:00:00Z',
    source: '2gis', aiRiskScore: 45,
  },
  {
    id: 'r6',
    branchId: 'b-taraz23',
    branchName: 'Аптека №23',
    branchAddress: 'мкр. Аса, 6а, Тараз',
    authorName: 'Alikhan',
    authorInitials: 'АЛ',
    rating: 5,
    text: 'Хорошая аптека! Очень вежливый персонал, всегда подскажут какое лекарство лучше, ответят на все вопросы. Доступные цены.',
    sentiment: 'positive', severity: 'low',
    categories: [],
    hasReply: true,
    replyText: 'Добрый день, Alikhan! Спасибо за высокую оценку! Всегда рады видеть вас.',
    publishedAt: '2025-05-01T12:00:00Z',
    source: '2gis', aiRiskScore: 5,
  },
  {
    id: 'r7',
    branchId: 'b-mamyr2',
    branchName: 'Садыхан',
    branchAddress: 'мкр. Мамыр-2, 3, Алматы',
    authorName: 'Сергей Ч.',
    authorInitials: 'СЧ',
    rating: 5,
    text: 'Прекрасная аптека, доступные цены, хорошие грамотные сотрудники. Цены нормальные, работает круглосуточно.',
    sentiment: 'positive', severity: 'low',
    categories: [],
    hasReply: true,
    publishedAt: '2025-05-10T15:00:00Z',
    source: 'yandex', aiRiskScore: 3,
  },
  {
    id: 'r8',
    branchId: 'b-bayterekova',
    branchName: 'Садыхан (соц. аптека)',
    branchAddress: 'ул. Байтерекова, 53, Алматы',
    authorName: 'Анонимный клиент',
    authorInitials: 'АК',
    rating: 1,
    text: 'Самый ужасный сервис в сети. Персонал хамит, никто ничего не знает. Уже третий раз такое.',
    sentiment: 'negative', severity: 'critical',
    categories: ['rudeness', 'consultation'],
    hasReply: false,
    publishedAt: '2025-05-18T08:00:00Z',
    source: '2gis', aiRiskScore: 96,
  },
]

export const COMPETITORS: Competitor[] = [
  { id: 'c1', name: 'Europharma', rating: 4.51, reviewCount: 5200, delta: 0.27, topStrength: 'Скорость, наличие товара', topWeakness: 'Цены выше среднего' },
  { id: 'c2', name: 'Планета Здоровья', rating: 4.30, reviewCount: 3100, delta: 0.06, topStrength: 'Ассортимент', topWeakness: 'Долгое ожидание' },
  { id: 'c3', name: 'Ромашка Аптека', rating: 4.18, reviewCount: 1800, delta: -0.06, topStrength: 'Цены', topWeakness: 'Мало филиалов' },
  { id: 'c4', name: 'Аптека 36.6', rating: 4.05, reviewCount: 2200, delta: -0.19, topStrength: 'Бренд', topWeakness: 'Грубость' },
  { id: 'c5', name: 'Ваша Аптека', rating: 3.92, reviewCount: 900, delta: -0.32, topStrength: 'Расположение', topWeakness: 'Ассортимент, сервис' },
]

export const ALERTS: AlertItem[] = [
  { id: 'a1', type: 'crisis', title: 'Байтерекова, 53 — рейтинг 2.3', description: '258 отзывов, большинство негативные. Худший филиал в сети.', branchId: 'b-bayterekova', branchName: 'Байтерекова, 53', createdAt: '2026-05-25T07:00:00Z', isRead: false },
  { id: 'a2', type: 'crisis', title: 'Аптека №17 — рейтинг 2.5', description: '163 отзыва. Системно низкий уровень обслуживания.', branchId: 'b-apt17', branchName: 'Аптека №17', createdAt: '2026-05-25T07:05:00Z', isRead: false },
  { id: 'a3', type: 'crisis', title: 'Аптека №9 — рейтинг 2.6', description: 'Жалобы на грубость персонала. Без ответа 65 отзывов.', branchId: 'b-apt9', branchName: 'Аптека №9', createdAt: '2026-05-25T07:10:00Z', isRead: false },
  { id: 'a4', type: 'warning', title: 'Аптека №12 — грубость фармацевта', description: 'Реальный отзыв из 2GIS — игнорирование клиентов. Без ответа.', branchId: 'b-apt12', branchName: 'Аптека №12', createdAt: '2026-05-24T09:30:00Z', isRead: false },
  { id: 'a5', type: 'warning', title: 'Системная проблема: цены vs Каспи', description: 'Клиенты активно сравнивают цены с Каспи. Несколько филиалов.', createdAt: '2026-05-23T14:00:00Z', isRead: true },
  { id: 'a6', type: 'info', title: 'Мамыр-2 — рейтинг 4.8 (лучший)', description: '329 отзывов, рост +0.4 за месяц. Используйте как эталон.', branchId: 'b-mamyr2', branchName: 'Мамыр-2', createdAt: '2026-05-22T10:00:00Z', isRead: true },
]

export const METRICS: DashboardMetrics = {
  avgRating: 3.48,
  avgRatingDelta: -0.14,
  totalReviews: 4182,
  totalReviewsDelta: 312,
  negativeCount: 1063,
  negativePercent: 25.4,
  unansweredCount: 567,
  avgResponseHours: 8.2,
  healthScore: 44,
  healthScoreDelta: -6,
  answeredPercent: 82,
  activeComplaints: 31,
}

export const RATING_HISTORY: RatingHistory[] = [
  { month: 'Июн 25', rating: 3.72, reviews: 290, negative: 58 },
  { month: 'Июл 25', rating: 3.68, reviews: 315, negative: 67 },
  { month: 'Авг 25', rating: 3.65, reviews: 340, negative: 72 },
  { month: 'Сен 25', rating: 3.60, reviews: 360, negative: 80 },
  { month: 'Окт 25', rating: 3.55, reviews: 380, negative: 88 },
  { month: 'Ноя 25', rating: 3.52, reviews: 370, negative: 85 },
  { month: 'Дек 25', rating: 3.50, reviews: 355, negative: 82 },
  { month: 'Янв 26', rating: 3.48, reviews: 395, negative: 98 },
  { month: 'Фев 26', rating: 3.45, reviews: 410, negative: 105 },
  { month: 'Мар 26', rating: 3.44, reviews: 420, negative: 108 },
  { month: 'Апр 26', rating: 3.46, reviews: 400, negative: 100 },
  { month: 'Май 26', rating: 3.48, reviews: 347, negative: 78 },
]

export const COMPLAINT_STATS: ComplaintStat[] = [
  { category: 'rudeness', label: 'Грубость персонала', count: 312, percent: 29.4 },
  { category: 'price', label: 'Цены выше рынка', count: 198, percent: 18.6 },
  { category: 'queue', label: 'Очередь / ожидание', count: 156, percent: 14.7 },
  { category: 'out_of_stock', label: 'Отсутствие товара', count: 134, percent: 12.6 },
  { category: 'phone', label: 'Телефон не отвечает', count: 98, percent: 9.2 },
  { category: 'schedule', label: 'Нарушение режима', count: 72, percent: 6.8 },
  { category: 'cleanliness', label: 'Чистота / запах', count: 45, percent: 4.2 },
  { category: 'expiry', label: 'Просрочка товара', count: 28, percent: 2.6 },
  { category: 'consultation', label: 'Неверная консультация', count: 19, percent: 1.8 },
]

export const AI_RESPONSE_TEMPLATES: Record<string, Record<string, string>> = {
  rudeness: {
    empathetic: 'Здравствуйте! Нам искренне жаль, что вы столкнулись с подобным отношением — это абсолютно недопустимо в нашей сети. Ваше обращение уже передано руководству филиала для немедленного разбора ситуации. Мы обязательно примем меры и свяжемся с вами лично. Спасибо, что нашли время сообщить нам об этом.',
    official: 'Уважаемый клиент, благодарим за обращение. Описанная ситуация является нарушением стандартов обслуживания SADYKHAN. Жалоба зарегистрирована и передана в отдел контроля качества. Меры будут приняты в течение 24 часов.',
    short: 'Приносим искренние извинения за недопустимое поведение сотрудника. Жалоба уже передана руководству — разберёмся и примем меры. Спасибо.',
  },
  price: {
    empathetic: 'Здравствуйте! Спасибо за внимательность и честный отзыв — мы ценим такую обратную связь. Цены в нашей сети формируются на основе закупочных условий и могут незначительно отличаться от маркетплейсов. Тем не менее мы передадим ваш отзыв коммерческому отделу для анализа конкурентоспособности.',
    official: 'Благодарим за обращение. Ценообразование в нашей сети регулируется внутренней политикой. Ваш отзыв передан в коммерческий отдел. Также рекомендуем использовать подписку SADYKHAN для получения дополнительных скидок.',
    short: 'Спасибо за отзыв! Понимаем ваше разочарование — передали информацию в коммерческий отдел. Наша подписка даёт дополнительные скидки.',
  },
  phone: {
    empathetic: 'Здравствуйте! Ужасно неприятно, что вам не удалось дозвониться — мы понимаем, насколько это важно при поиске лекарств. Ситуация уже передана управляющему филиала. Также вы можете проверить наличие товара на сайте sadykhan.kz или в нашем приложении.',
    official: 'Уважаемый клиент, благодарим за обращение. Проблема доступности телефонной линии передана в технический отдел. Для срочных запросов рекомендуем использовать онлайн-чат на сайте sadykhan.kz.',
    short: 'Извините за неудобство! Передали управляющему. Наличие также можно проверить на sadykhan.kz.',
  },
}
